export default {
  GAMES: 'GAMES',
  GAMES_LAST_MONTH: 'GAMES_LAST_MONTH',
  GAMES_RELEASED: 'GAMES_RELEASED',
  CURRENT_PAGE: 'CURRENT_PAGE',
  TOTAL_RESULTS: 'TOTAL_RESULTS',
  TOTAL_RESULTS_LAST_MONTH: 'TOTAL_RESULTS_LAST_MONTH',
  CURRENT_QUERY: 'CURRENT_QUERY',
};
